bep: bnb chain fusion
bnb-chain/BEPs pull request #333
Opened 2023-11-29 07:51 UTC by forcodedancing

2024-01-10 16:47 UTC, CripTz00 approved these changes

2024-01-14 01:14 UTC, dogus1710 approved these changes

2024-01-21 15:10 UTC, nael7777 commented
forcodedancing:chain_fusion

2024-01-27 23:12 UTC, waleed8y commented
> <pre>
>   BEP: 333
>   Title: BNB Chain Fusion
>   Status: Draft
>   Type: Standards
>   Created: 2023-11-29
> </pre>
> 
> # BEP-333: BNB Chain Fusion
> 
> [BEP-333: BNB Chain Fusion](#bep-333-bnb-chain-fusion)
>   - [1. Summary](#1-summary)
>   - [2. Abstract](#2-abstract)
>   - [3. Status](#3-status)
>   - [4. Motivation](#4-motivation)
>   - [5. Specification](#5-specification)
>       - [5.1 Introduction](#51-introduction)
>       - [5.2 Multiple Phases](#52-multiple-phases)
>   - [6. License](#6-license)
> 
> ## 1. Summary
> 
> This BEP proposes to securely and smoothly transit the BNB Beacon Chain and BNB Smart Chain (BSC) from a dual-chain structure into a single chain structure and decommission the Beacon Chain.
> 
> ## 2. Abstract
> 
> BNB Chain Fusion (BC Fusion) is a major achievement for BNB Chain. It helps overcome legacy services and technical debt, enabling faster iteration and development. BC Fusion includes three sub-BEPs:
> 
> - [BEP-294: BSC Native Staking](https://github.com/bnb-chain/BEPs/pull/294)
> 
> - [BEP-297: BSC Native Governance](https://github.com/bnb-chain/BEPs/pull/297)
> 
> - [BEP-299: Token Migration after BC Fusion](https://github.com/bnb-chain/BEPs/pull/299)
> 
> This BEP primarily proposes strategic planning and coordination for organizing these BEPs. The goal is to facilitate the secure and seamless implementation of BC Fusion.
> 
> ## 3. Status
> 
> This BEP is a draft.
> 
> ## 4. Motivation
> 
> BNB Beacon Chain is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. Besides this, Beacon Chain and BSC is a dual-chain structure: Beacon Chain helps to enhance the security of BSC as a staking and governance layer. With the rise of various other forms of Dex, order-book based decentralized exchange was decommissioned in [BEP151](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP151.md). With the quick evolution of BSC, the Beacon Chain has become a burden. The cross-chain bridge that connects the two chains slows down the development iteration and always exposes BNB to a certain level of security vulnerabilities. It\'s time to take a step further and migrate the functionality of Beacon Chain to BSC, allowing Beacon Chain to retire.
> 
> ## 5. Specification
> 
> ### 5.1 Introduction
> 
> The Beacon Chain currently possesses several key functionalities:
> 
> 1. Cryptocurrency management platform. The Beacon Chain mainnet currently supports a hundred kinds of [BEP2](https://explorer.bnbchain.org/assets/bep2) and [BEP8](https://explorer.bnbchain.org/assets/bep8) tokens. These tokens have value and can be circulated on the Beacon Chain or transferred across different chains using protocols such as [BEP3](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP3.md).
> 
> 2. The staking layer of BSC. The BSC utilizes the POSA consensus algorithm. It delegates staking election and reward distribution functions to the Beacon Chain. This design choice was based on the fact that the Beacon Chain is built on the cosmos-sdk architecture, which already includes a well-developed staking module that can be reused.
> 
> 3. The governance layer of BSC. For similar reasons, the governance functionality of BSC is delegated to the Beacon Chain as well. The governance vote and tally happen on Beacon Chain, and the execution plan is delivered to the BSC through cross chain communication protocol.
> 
> Therefore, we have three separate BEPs that discuss how to migrate these functionalities or valuable assets to BSC.
> 
> 1. [BEP-299](https://github.com/bnb-chain/BEPs/pull/299): This BEP presents a secure and trustless way for users to recover their assets on the BSC once the Beacon chain stops running.
> 
> 2. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294): This BEP allows BNB holders to stake BNB to the specified validators and get staking rewards on the BSC side directly. To ensure network security, the migration of Staking voting power is designed to be seamless. This means that both the Beacon Chain and BSC\'s staking modules will coexist and function simultaneously during the migration process.
> 
> 3. [BEP297](https://github.com/bnb-chain/BEPs/pull/297): This BEP allows community members to submit proposals directly on the BSC network. The governance module is fully compatible with [Tally](https://www.tally.xyz/).
> 
> ### 5.2 Multiple Phases
> 
> To accomplish BC Fusion, there will be several preparation and post-action steps involved, connecting these BEPs together. Thus, BC Fusion is divided into multiple stages:
> 
> ![multiple phases](https://raw.githubusercontent.com/bnb-chain/BEPs/9649944c2a41b05e5ca59d5fa18b592a0ee600ee/BEPs/assets/bep-333/phases.png)
> 
> #### 5.2.1 First Sunset Fork
> 
> Due to the requirement of returning cryptocurrency to the user\'s wallet in order to migrate funds to BSC through [BEP-299](https://github.com/bnb-chain/BEPs/pull/299). The Beacon Chain will disable specific types of transactions to encourage users to keep their funds in their own wallets. The following types of Beacon chain transactions will be disabled: **TimeLockMsg**, **TimeRelockMsg**, **FreezeMsg**, **IssueMsg**, **MintMsg**, **IssueMiniMsg**, **HTLTMsg**, **DepositHTLTMsg**.
> 
> During the migration process, Beacon Chain prohibits the creation and editing of validators to prevent conflicts with validators created on BSC side. New delegations will also be prohibited. The following types of Beacon chain transactions will be disabled: **MsgCreateValidatorOpen**, **MsgCreateSideChainValidator**, **MsgCreateSideChainValidatorWithVoteAddr**, **MsgEditSideChainValidatorWithVoteAddr**, **MsgSideChainDelegate**, **MsgSideChainReDelegate**.
> 
> To ensure that the voting power migration process is not maliciously manipulated, the Governance module will be automatically disabled when the voting power is below 5M BNB.
> 
> The above-mentioned features will be enabled in Beacon Chain **FirstSunsetFork**.
> 
> #### 5.2.2 BSC Feynman Hardfork
> 
> [BEP-294](https://github.com/bnb-chain/BEPs/pull/294), [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) and [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) will be deployed in the BSC **Feynman** hard fork.
> 
> 1. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) will take effect immediately. Validators created on BSC will receive triple voting power when staking an equal amount of BNB. This encourages the transfer of voting power from the Beacon Chain to BSC.
> 
> 2. The [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) governance functionality will not be activated immediately after the hardfork. It will only be automatically enabled once more than 10 million BNB are migrated to BSC.
> 
> 3. The smart contract of [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) is not available as the merkel root in the smart contract is still empty at this time. Only after the Beacon Chain comes to a complete halt, the Token Migration feature will be initiated by setting the Merkle root for balance dump through governance.
> 
> 4. Cross-chain re-delegation, which allows users to un-delegate their stakes from Beacon Chain and then delegate them on BSC in one Beacon Chain transaction,  will be enabled after governance opening the related cross-chain channel.
> 
> An important wallet will be introduced in this hardfork: **AssetProtector.** **AssetProtector** is a multi-signature wallet controlled by the core dev team at the beginning. It can:
> 
> - Pause and unpause the staking, governance and token migration contract in emergency situations.
> 
> - Forbidden a specific account to perform any operations in the staking contract.
> 
> #### 5.2.3 Second Sunset Fork
> 
> After transferring more than two-thirds of the voting power to BSC, the Beacon Chain must restrict additional transaction types and automatically execute specific logic to ensure the return of funds to users\' wallets. The following transactio [...]

2024-01-31 07:14 UTC, GStar718 commented
Is there anyone in this community willing to help me out with this project please and I will be very grateful thank you

2024-02-05 05:12 UTC, GStar718 commented
I'm so confused

2024-02-10 23:33 UTC, GrayFieth approved these changes

2024-02-17 18:04 UTC, Fdutoit96 approved these changes

2024-02-27 06:22 UTC, zjubfd approved these changes

2024-02-27 06:22 UTC, merged

2024-02-27 07:06 UTC, Thembks commented
♥️

2024-03-09 19:40 UTC, draghtnight reviewed
The

2024-03-24 09:00 UTC, Queenkaz reviewed
🤟🏽

2024-03-24 12:10 UTC, draghtnight reviewed
Duplicate of #

2024-03-30 21:18 UTC, suchat932 reviewed
BEPs/BEP333.md

2024-04-15 15:10 UTC, Gabo139 approved these changes

2024-04-23 22:49 UTC, GrayFieth commented
Merge Master

2024-04-24 22:38 UTC, Thembks commented
2

2024-04-25 20:18 UTC, De254 commented
Very nice

2024-04-27 16:00 UTC, Alirastgoo67 reviewed
A

2024-05-14 20:30 UTC, PayamShahmansour approved these changes

2024-05-15 17:18 UTC, hafizulsaat92 approved these changes

2024-05-16 22:34 UTC, lunaxz commented
Hi

2024-06-05 12:04 UTC, SamyDgz approved these changes

2024-06-06 20:37 UTC, Jircs1 reviewed
great work!!!

2024-06-21 00:50 UTC, Alximm approved these changes

2024-06-22 12:57 UTC, Nichebiche commented
> BEP: 333
>   Title: BNB Chain Fusion
>   Status: Draft
>   Type: Standards
>   Created: 2023-11-29
> # BEP-333: BNB Chain Fusion
> [BEP-333: BNB Chain Fusion](#bep-333-bnb-chain-fusion)
> 
> * [1. Summary](#1-summary)
> * [2. Abstract](#2-abstract)
> * [3. Status](#3-status)
> * [4. Motivation](#4-motivation)
> * [5. Specification](#5-specification)
>   
>   * [5.1 Introduction](#51-introduction)
>   * [5.2 Multiple Phases](#52-multiple-phases)
> * [6. License](#6-license)
> 
> ## 1. Summary
> This BEP proposes to securely and smoothly transit the BNB Beacon Chain and BNB Smart Chain (BSC) from a dual-chain structure into a single chain structure and decommission the Beacon Chain.
> 
> ## 2. Abstract
> BNB Chain Fusion (BC Fusion) is a major achievement for BNB Chain. It helps overcome legacy services and technical debt, enabling faster iteration and development. BC Fusion includes three sub-BEPs:
> 
> * [BEP-294: BSC Native Staking](https://github.com/bnb-chain/BEPs/pull/294)
> * [BEP-297: BSC Native Governance](https://github.com/bnb-chain/BEPs/pull/297)
> * [BEP-299: Token Migration after BC Fusion](https://github.com/bnb-chain/BEPs/pull/299)
> 
> This BEP primarily proposes strategic planning and coordination for organizing these BEPs. The goal is to facilitate the secure and seamless implementation of BC Fusion.
> 
> ## 3. Status
> This BEP is a draft.
> 
> ## 4. Motivation
> BNB Beacon Chain is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. Besides this, Beacon Chain and BSC is a dual-chain structure: Beacon Chain helps to enhance the security of BSC as a staking and governance layer. With the rise of various other forms of Dex, order-book based decentralized exchange was decommissioned in [BEP151](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP151.md). With the quick evolution of BSC, the Beacon Chain has become a burden. The cross-chain bridge that connects the two chains slows down the development iteration and always exposes BNB to a certain level of security vulnerabilities. It's time to take a step further and migrate the functionality of Beacon Chain to BSC, allowing Beacon Chain to retire.
> 
> ## 5. Specification
> ### 5.1 Introduction
> The Beacon Chain currently possesses several key functionalities:
> 
> 1. Cryptocurrency management platform. The Beacon Chain mainnet currently supports a hundred kinds of [BEP2](https://explorer.bnbchain.org/assets/bep2) and [BEP8](https://explorer.bnbchain.org/assets/bep8) tokens. These tokens have value and can be circulated on the Beacon Chain or transferred across different chains using protocols such as [BEP3](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP3.md).
> 2. The staking layer of BSC. The BSC utilizes the POSA consensus algorithm. It delegates staking election and reward distribution functions to the Beacon Chain. This design choice was based on the fact that the Beacon Chain is built on the cosmos-sdk architecture, which already includes a well-developed staking module that can be reused.
> 3. The governance layer of BSC. For similar reasons, the governance functionality of BSC is delegated to the Beacon Chain as well. The governance vote and tally happen on Beacon Chain, and the execution plan is delivered to the BSC through cross chain communication protocol.
> 
> Therefore, we have three separate BEPs that discuss how to migrate these functionalities or valuable assets to BSC.
> 
> 1. [BEP-299](https://github.com/bnb-chain/BEPs/pull/299): This BEP presents a secure and trustless way for users to recover their assets on the BSC once the Beacon chain stops running.
> 2. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294): This BEP allows BNB holders to stake BNB to the specified validators and get staking rewards on the BSC side directly. To ensure network security, the migration of Staking voting power is designed to be seamless. This means that both the Beacon Chain and BSC's staking modules will coexist and function simultaneously during the migration process.
> 3. [BEP297](https://github.com/bnb-chain/BEPs/pull/297): This BEP allows community members to submit proposals directly on the BSC network. The governance module is fully compatible with [Tally](https://www.tally.xyz/).
> 
> ### 5.2 Multiple Phases
> To accomplish BC Fusion, there will be several preparation and post-action steps involved, connecting these BEPs together. Thus, BC Fusion is divided into multiple stages:
> 
> ![multiple phases](https://raw.githubusercontent.com/bnb-chain/BEPs/9649944c2a41b05e5ca59d5fa18b592a0ee600ee/BEPs/assets/bep-333/phases.png)
> 
> #### 5.2.1 First Sunset Fork
> Due to the requirement of returning cryptocurrency to the user's wallet in order to migrate funds to BSC through [BEP-299](https://github.com/bnb-chain/BEPs/pull/299). The Beacon Chain will disable specific types of transactions to encourage users to keep their funds in their own wallets. The following types of Beacon chain transactions will be disabled: **TimeLockMsg**, **TimeRelockMsg**, **FreezeMsg**, **IssueMsg**, **MintMsg**, **IssueMiniMsg**, **HTLTMsg**, **DepositHTLTMsg**.
> 
> During the migration process, Beacon Chain prohibits the creation and editing of validators to prevent conflicts with validators created on BSC side. New delegations will also be prohibited. The following types of Beacon chain transactions will be disabled: **MsgCreateValidatorOpen**, **MsgCreateSideChainValidator**, **MsgCreateSideChainValidatorWithVoteAddr**, **MsgEditSideChainValidatorWithVoteAddr**, **MsgSideChainDelegate**, **MsgSideChainReDelegate**.
> 
> To ensure that the voting power migration process is not maliciously manipulated, the Governance module will be automatically disabled when the voting power is below 5M BNB.
> 
> The above-mentioned features will be enabled in Beacon Chain **FirstSunsetFork**.
> 
> #### 5.2.2 BSC Feynman Hardfork
> [BEP-294](https://github.com/bnb-chain/BEPs/pull/294), [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) and [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) will be deployed in the BSC **Feynman** hard fork.
> 
> 1. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) will take effect immediately. Validators created on BSC will receive triple voting power when staking an equal amount of BNB. This encourages the transfer of voting power from the Beacon Chain to BSC.
> 2. The [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) governance functionality will not be activated immediately after the hardfork. It will only be automatically enabled once more than 10 million BNB are migrated to BSC.
> 3. The smart contract of [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) is not available as the merkel root in the smart contract is still empty at this time. Only after the Beacon Chain comes to a complete halt, the Token Migration feature will be initiated by setting the Merkle root for balance dump through governance.
> 4. Cross-chain re-delegation, which allows users to un-delegate their stakes from Beacon Chain and then delegate them on BSC in one Beacon Chain transaction,  will be enabled after governance opening the related cross-chain channel.
> 
> An important wallet will be introduced in this hardfork: **AssetProtector.** **AssetProtector** is a multi-signature wallet controlled by the core dev team at the beginning. It can:
> 
> * Pause and unpause the staking, governance and token migration contract in emergency situations.
> * Forbidden a specific account to perform any operations in the staking contract.
> 
> #### 5.2.3 Second Sunset Fork
> After transferring more than two-thirds of the voting power to BSC, the Beacon Chain must restrict additional transaction types and automatically execute specific logic to ensure the return of funds to users' wallets. The following transactions will be disabled: **MsgSideChainSubmitProposal**.
> 
> All TimeLock and AtomicSwap will automatica [...]

2024-06-24 01:29 UTC, AungThuSoe24 reviewed
OKX.com

2024-06-24 01:40 UTC, Nichebiche commented
Got it.


Sent from Yahoo Mail for iPhone


On Sunday, June 23, 2024, 9:29 PM, AungThuSoe24 ***@***.***> wrote:




@AungThuSoe24 commented on this pull request.

OKX.com

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

2024-06-26 17:51 UTC, Carlo0704 approved these changes

2024-06-26 21:03 UTC, Nichebiche commented
Thank you

2024-06-29 09:26 UTC, William57575757 approved these changes

2024-06-29 09:27 UTC, William57575757 approved these changes

2024-07-10 00:03 UTC, Wachira3712 reviewed
มิตรภาพ ถาวร

2024-07-22 23:32 UTC, Nidacoke commented
forcodedancing:chain_fusion

2024-07-30 00:13 UTC, Rachale43 approved these changes

2024-08-06 20:04 UTC, lazoran commented
I can not get my BEP2 out of the BNB Beacon chain because I dont have BNB for gas. It seems like the devs have already disabled incoming transactions as I cant send any BNB to that wallet. How can I manually get my assets out and moved? I cant find help anywhere

2024-08-10 19:03 UTC, yener35 commented
methaba

2024-08-10 19:04 UTC, yener35 commented
[]()

2024-08-10 19:08 UTC, Nichebiche commented
What


Sent from Yahoo Mail for iPhone


On Saturday, August 10, 2024, 3:04 PM, yener35 ***@***.***> wrote:




methaba

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

2024-08-10 19:21 UTC, yener35 commented
****

2024-08-16 15:25 UTC, octavio12345300 commented
>

2024-08-16 16:48 UTC, octavio12345300 approved these changes

2024-08-18 07:45 UTC, octavio12345300 commented on BEPs/BEP333.md
> -- [BEP-294: BSC Native Staking after BC](https://github.com/bnb-chain/BEPs/pull/294)
```

```

2024-08-22 12:50 UTC, Elgayar777 reviewed
Ok

2024-08-25 08:09 UTC, hasti0073 commented
> <pre>
>   BEP: 333
>   Title: BNB Chain Fusion
>   Status: Draft
>   Type: Standards
>   Created: 2023-11-29
> </pre>
> 
> # BEP-333: BNB Chain Fusion
> 
> [BEP-333: BNB Chain Fusion](#bep-333-bnb-chain-fusion)
>   - [1. Summary](#1-summary)
>   - [2. Abstract](#2-abstract)
>   - [3. Status](#3-status)
>   - [4. Motivation](#4-motivation)
>   - [5. Specification](#5-specification)
>       - [5.1 Introduction](#51-introduction)
>       - [5.2 Multiple Phases](#52-multiple-phases)
>   - [6. License](#6-license)
> 
> ## 1. Summary
> 
> This BEP proposes to securely and smoothly transit the BNB Beacon Chain and BNB Smart Chain (BSC) from a dual-chain structure into a single chain structure and decommission the Beacon Chain.
> 
> ## 2. Abstract
> 
> BNB Chain Fusion (BC Fusion) is a major achievement for BNB Chain. It helps overcome legacy services and technical debt, enabling faster iteration and development. BC Fusion includes three sub-BEPs:
> 
> - [BEP-294: BSC Native Staking](https://github.com/bnb-chain/BEPs/pull/294)
> 
> - [BEP-297: BSC Native Governance](https://github.com/bnb-chain/BEPs/pull/297)
> 
> - [BEP-299: Token Migration after BC Fusion](https://github.com/bnb-chain/BEPs/pull/299)
> 
> This BEP primarily proposes strategic planning and coordination for organizing these BEPs. The goal is to facilitate the secure and seamless implementation of BC Fusion.
> 
> ## 3. Status
> 
> This BEP is a draft.
> 
> ## 4. Motivation
> 
> BNB Beacon Chain is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. Besides this, Beacon Chain and BSC is a dual-chain structure: Beacon Chain helps to enhance the security of BSC as a staking and governance layer. With the rise of various other forms of Dex, order-book based decentralized exchange was decommissioned in [BEP151](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP151.md). With the quick evolution of BSC, the Beacon Chain has become a burden. The cross-chain bridge that connects the two chains slows down the development iteration and always exposes BNB to a certain level of security vulnerabilities. It\'s time to take a step further and migrate the functionality of Beacon Chain to BSC, allowing Beacon Chain to retire.
> 
> ## 5. Specification
> 
> ### 5.1 Introduction
> 
> The Beacon Chain currently possesses several key functionalities:
> 
> 1. Cryptocurrency management platform. The Beacon Chain mainnet currently supports a hundred kinds of [BEP2](https://explorer.bnbchain.org/assets/bep2) and [BEP8](https://explorer.bnbchain.org/assets/bep8) tokens. These tokens have value and can be circulated on the Beacon Chain or transferred across different chains using protocols such as [BEP3](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP3.md).
> 
> 2. The staking layer of BSC. The BSC utilizes the POSA consensus algorithm. It delegates staking election and reward distribution functions to the Beacon Chain. This design choice was based on the fact that the Beacon Chain is built on the cosmos-sdk architecture, which already includes a well-developed staking module that can be reused.
> 
> 3. The governance layer of BSC. For similar reasons, the governance functionality of BSC is delegated to the Beacon Chain as well. The governance vote and tally happen on Beacon Chain, and the execution plan is delivered to the BSC through cross chain communication protocol.
> 
> Therefore, we have three separate BEPs that discuss how to migrate these functionalities or valuable assets to BSC.
> 
> 1. [BEP-299](https://github.com/bnb-chain/BEPs/pull/299): This BEP presents a secure and trustless way for users to recover their assets on the BSC once the Beacon chain stops running.
> 
> 2. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294): This BEP allows BNB holders to stake BNB to the specified validators and get staking rewards on the BSC side directly. To ensure network security, the migration of Staking voting power is designed to be seamless. This means that both the Beacon Chain and BSC\'s staking modules will coexist and function simultaneously during the migration process.
> 
> 3. [BEP297](https://github.com/bnb-chain/BEPs/pull/297): This BEP allows community members to submit proposals directly on the BSC network. The governance module is fully compatible with [Tally](https://www.tally.xyz/).
> 
> ### 5.2 Multiple Phases
> 
> To accomplish BC Fusion, there will be several preparation and post-action steps involved, connecting these BEPs together. Thus, BC Fusion is divided into multiple stages:
> 
> ![multiple phases](https://raw.githubusercontent.com/bnb-chain/BEPs/9649944c2a41b05e5ca59d5fa18b592a0ee600ee/BEPs/assets/bep-333/phases.png)
> 
> #### 5.2.1 First Sunset Fork
> 
> Due to the requirement of returning cryptocurrency to the user\'s wallet in order to migrate funds to BSC through [BEP-299](https://github.com/bnb-chain/BEPs/pull/299). The Beacon Chain will disable specific types of transactions to encourage users to keep their funds in their own wallets. The following types of Beacon chain transactions will be disabled: **TimeLockMsg**, **TimeRelockMsg**, **FreezeMsg**, **IssueMsg**, **MintMsg**, **IssueMiniMsg**, **HTLTMsg**, **DepositHTLTMsg**.
> 
> During the migration process, Beacon Chain prohibits the creation and editing of validators to prevent conflicts with validators created on BSC side. New delegations will also be prohibited. The following types of Beacon chain transactions will be disabled: **MsgCreateValidatorOpen**, **MsgCreateSideChainValidator**, **MsgCreateSideChainValidatorWithVoteAddr**, **MsgEditSideChainValidatorWithVoteAddr**, **MsgSideChainDelegate**, **MsgSideChainReDelegate**.
> 
> To ensure that the voting power migration process is not maliciously manipulated, the Governance module will be automatically disabled when the voting power is below 5M BNB.
> 
> The above-mentioned features will be enabled in Beacon Chain **FirstSunsetFork**.
> 
> #### 5.2.2 BSC Feynman Hardfork
> 
> [BEP-294](https://github.com/bnb-chain/BEPs/pull/294), [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) and [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) will be deployed in the BSC **Feynman** hard fork.
> 
> 1. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) will take effect immediately. Validators created on BSC will receive triple voting power when staking an equal amount of BNB. This encourages the transfer of voting power from the Beacon Chain to BSC.
> 
> 2. The [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) governance functionality will not be activated immediately after the hardfork. It will only be automatically enabled once more than 10 million BNB are migrated to BSC.
> 
> 3. The smart contract of [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) is not available as the merkel root in the smart contract is still empty at this time. Only after the Beacon Chain comes to a complete halt, the Token Migration feature will be initiated by setting the Merkle root for balance dump through governance.
> 
> 4. Cross-chain re-delegation, which allows users to un-delegate their stakes from Beacon Chain and then delegate them on BSC in one Beacon Chain transaction,  will be enabled after governance opening the related cross-chain channel.
> 
> An important wallet will be introduced in this hardfork: **AssetProtector.** **AssetProtector** is a multi-signature wallet controlled by the core dev team at the beginning. It can:
> 
> - Pause and unpause the staking, governance and token migration contract in emergency situations.
> 
> - Forbidden a specific account to perform any operations in the staking contract.
> 
> #### 5.2.3 Second Sunset Fork
> 
> After transferring more than two-thirds of the voting power to BSC, the Beacon Chain must restrict additional transaction types and automatically execute specific logic to ensure the return of funds to users\' wallets. The following transactio [...]

2024-08-25 08:10 UTC, hasti0073 approved these changes

2024-09-04 09:17 UTC, yener35 commented
yener

2024-09-04 16:56 UTC, yener35 commented
ynr

2024-09-05 10:37 UTC, yener35 commented
ynr

2024-09-07 00:31 UTC, thuthu24 commented
Thuthu24

2024-09-08 21:20 UTC, Alkhtri77 approved these changes

2024-09-08 21:22 UTC, yener35 commented
****

2024-09-09 05:23 UTC, Elgayar777 reviewed
.

2024-09-18 18:06 UTC, hasti0073 reviewed
o

2024-09-18 19:26 UTC, hasti0073 commented
> <pre>
>   BEP: 333
>   Title: BNB Chain Fusion
>   Status: Draft
>   Type: Standards
>   Created: 2023-11-29
> </pre>
> 
> # BEP-333: BNB Chain Fusion
> 
> [BEP-333: BNB Chain Fusion](#bep-333-bnb-chain-fusion)
>   - [1. Summary](#1-summary)
>   - [2. Abstract](#2-abstract)
>   - [3. Status](#3-status)
>   - [4. Motivation](#4-motivation)
>   - [5. Specification](#5-specification)
>       - [5.1 Introduction](#51-introduction)
>       - [5.2 Multiple Phases](#52-multiple-phases)
>   - [6. License](#6-license)
> 
> ## 1. Summary
> 
> This BEP proposes to securely and smoothly transit the BNB Beacon Chain and BNB Smart Chain (BSC) from a dual-chain structure into a single chain structure and decommission the Beacon Chain.
> 
> ## 2. Abstract
> 
> BNB Chain Fusion (BC Fusion) is a major achievement for BNB Chain. It helps overcome legacy services and technical debt, enabling faster iteration and development. BC Fusion includes three sub-BEPs:
> 
> - [BEP-294: BSC Native Staking](https://github.com/bnb-chain/BEPs/pull/294)
> 
> - [BEP-297: BSC Native Governance](https://github.com/bnb-chain/BEPs/pull/297)
> 
> - [BEP-299: Token Migration after BC Fusion](https://github.com/bnb-chain/BEPs/pull/299)
> 
> This BEP primarily proposes strategic planning and coordination for organizing these BEPs. The goal is to facilitate the secure and seamless implementation of BC Fusion.
> 
> ## 3. Status
> 
> This BEP is a draft.
> 
> ## 4. Motivation
> 
> BNB Beacon Chain is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. Besides this, Beacon Chain and BSC is a dual-chain structure: Beacon Chain helps to enhance the security of BSC as a staking and governance layer. With the rise of various other forms of Dex, order-book based decentralized exchange was decommissioned in [BEP151](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP151.md). With the quick evolution of BSC, the Beacon Chain has become a burden. The cross-chain bridge that connects the two chains slows down the development iteration and always exposes BNB to a certain level of security vulnerabilities. It\'s time to take a step further and migrate the functionality of Beacon Chain to BSC, allowing Beacon Chain to retire.
> 
> ## 5. Specification
> 
> ### 5.1 Introduction
> 
> The Beacon Chain currently possesses several key functionalities:
> 
> 1. Cryptocurrency management platform. The Beacon Chain mainnet currently supports a hundred kinds of [BEP2](https://explorer.bnbchain.org/assets/bep2) and [BEP8](https://explorer.bnbchain.org/assets/bep8) tokens. These tokens have value and can be circulated on the Beacon Chain or transferred across different chains using protocols such as [BEP3](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP3.md).
> 
> 2. The staking layer of BSC. The BSC utilizes the POSA consensus algorithm. It delegates staking election and reward distribution functions to the Beacon Chain. This design choice was based on the fact that the Beacon Chain is built on the cosmos-sdk architecture, which already includes a well-developed staking module that can be reused.
> 
> 3. The governance layer of BSC. For similar reasons, the governance functionality of BSC is delegated to the Beacon Chain as well. The governance vote and tally happen on Beacon Chain, and the execution plan is delivered to the BSC through cross chain communication protocol.
> 
> Therefore, we have three separate BEPs that discuss how to migrate these functionalities or valuable assets to BSC.
> 
> 1. [BEP-299](https://github.com/bnb-chain/BEPs/pull/299): This BEP presents a secure and trustless way for users to recover their assets on the BSC once the Beacon chain stops running.
> 
> 2. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294): This BEP allows BNB holders to stake BNB to the specified validators and get staking rewards on the BSC side directly. To ensure network security, the migration of Staking voting power is designed to be seamless. This means that both the Beacon Chain and BSC\'s staking modules will coexist and function simultaneously during the migration process.
> 
> 3. [BEP297](https://github.com/bnb-chain/BEPs/pull/297): This BEP allows community members to submit proposals directly on the BSC network. The governance module is fully compatible with [Tally](https://www.tally.xyz/).
> 
> ### 5.2 Multiple Phases
> 
> To accomplish BC Fusion, there will be several preparation and post-action steps involved, connecting these BEPs together. Thus, BC Fusion is divided into multiple stages:
> 
> ![multiple phases](https://raw.githubusercontent.com/bnb-chain/BEPs/9649944c2a41b05e5ca59d5fa18b592a0ee600ee/BEPs/assets/bep-333/phases.png)
> 
> #### 5.2.1 First Sunset Fork
> 
> Due to the requirement of returning cryptocurrency to the user\'s wallet in order to migrate funds to BSC through [BEP-299](https://github.com/bnb-chain/BEPs/pull/299). The Beacon Chain will disable specific types of transactions to encourage users to keep their funds in their own wallets. The following types of Beacon chain transactions will be disabled: **TimeLockMsg**, **TimeRelockMsg**, **FreezeMsg**, **IssueMsg**, **MintMsg**, **IssueMiniMsg**, **HTLTMsg**, **DepositHTLTMsg**.
> 
> During the migration process, Beacon Chain prohibits the creation and editing of validators to prevent conflicts with validators created on BSC side. New delegations will also be prohibited. The following types of Beacon chain transactions will be disabled: **MsgCreateValidatorOpen**, **MsgCreateSideChainValidator**, **MsgCreateSideChainValidatorWithVoteAddr**, **MsgEditSideChainValidatorWithVoteAddr**, **MsgSideChainDelegate**, **MsgSideChainReDelegate**.
> 
> To ensure that the voting power migration process is not maliciously manipulated, the Governance module will be automatically disabled when the voting power is below 5M BNB.
> 
> The above-mentioned features will be enabled in Beacon Chain **FirstSunsetFork**.
> 
> #### 5.2.2 BSC Feynman Hardfork
> 
> [BEP-294](https://github.com/bnb-chain/BEPs/pull/294), [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) and [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) will be deployed in the BSC **Feynman** hard fork.
> 
> 1. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) will take effect immediately. Validators created on BSC will receive triple voting power when staking an equal amount of BNB. This encourages the transfer of voting power from the Beacon Chain to BSC.
> 
> 2. The [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) governance functionality will not be activated immediately after the hardfork. It will only be automatically enabled once more than 10 million BNB are migrated to BSC.
> 
> 3. The smart contract of [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) is not available as the merkel root in the smart contract is still empty at this time. Only after the Beacon Chain comes to a complete halt, the Token Migration feature will be initiated by setting the Merkle root for balance dump through governance.
> 
> 4. Cross-chain re-delegation, which allows users to un-delegate their stakes from Beacon Chain and then delegate them on BSC in one Beacon Chain transaction,  will be enabled after governance opening the related cross-chain channel.
> 
> An important wallet will be introduced in this hardfork: **AssetProtector.** **AssetProtector** is a multi-signature wallet controlled by the core dev team at the beginning. It can:
> 
> - Pause and unpause the staking, governance and token migration contract in emergency situations.
> 
> - Forbidden a specific account to perform any operations in the staking contract.
> 
> #### 5.2.3 Second Sunset Fork
> 
> After transferring more than two-thirds of the voting power to BSC, the Beacon Chain must restrict additional transaction types and automatically execute specific logic to ensure the return of funds to users\' wallets. The following transactio [...]

2024-09-25 22:53 UTC, octavio12345300 approved these changes

2024-09-25 22:53 UTC, octavio12345300 commented
Gracias

2024-09-28 04:28 UTC, yener35 commented
[](https://pin.it/4ZfDAsB6Y)

2024-09-28 08:55 UTC, octavio12345300 approved these changes

2024-09-28 08:55 UTC, octavio12345300 approved these changes

2024-09-29 23:47 UTC, octavio12345300 approved these changes

2024-09-30 07:32 UTC, octavio12345300 reviewed
gracias

2024-09-30 07:50 UTC, hasti0073 commented
> yener

2024-10-09 22:25 UTC, WojasKrk approved these changes

2024-10-10 23:09 UTC, octavio12345300 commented
0xf9fe553510ae4a4cc88ca5ea72f388f3da20cb0b

2024-10-10 23:09 UTC, octavio12345300 approved these changes

2024-10-11 19:59 UTC, dogus1710 reviewed
Ready

2024-10-17 21:17 UTC, Gaser811 commented
> BEP: 333
>   Title: BNB Chain Fusion
>   Status: Draft
>   Type: Standards
>   Created: 2023-11-29
> # BEP-333: BNB Chain Fusion
> [BEP-333: BNB Chain Fusion](#bep-333-bnb-chain-fusion)
> 
> * [1. Summary](#1-summary)
> * [2. Abstract](#2-abstract)
> * [3. Status](#3-status)
> * [4. Motivation](#4-motivation)
> * [5. Specification](#5-specification)
>   
>   * [5.1 Introduction](#51-introduction)
>   * [5.2 Multiple Phases](#52-multiple-phases)
> * [6. License](#6-license)
> 
> ## 1. Summary
> This BEP proposes to securely and smoothly transit the BNB Beacon Chain and BNB Smart Chain (BSC) from a dual-chain structure into a single chain structure and decommission the Beacon Chain.
> 
> ## 2. Abstract
> BNB Chain Fusion (BC Fusion) is a major achievement for BNB Chain. It helps overcome legacy services and technical debt, enabling faster iteration and development. BC Fusion includes three sub-BEPs:
> 
> * [BEP-294: BSC Native Staking](https://github.com/bnb-chain/BEPs/pull/294)
> * [BEP-297: BSC Native Governance](https://github.com/bnb-chain/BEPs/pull/297)
> * [BEP-299: Token Migration after BC Fusion](https://github.com/bnb-chain/BEPs/pull/299)
> 
> This BEP primarily proposes strategic planning and coordination for organizing these BEPs. The goal is to facilitate the secure and seamless implementation of BC Fusion.
> 
> ## 3. Status
> This BEP is a draft.
> 
> ## 4. Motivation
> BNB Beacon Chain is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. Besides this, Beacon Chain and BSC is a dual-chain structure: Beacon Chain helps to enhance the security of BSC as a staking and governance layer. With the rise of various other forms of Dex, order-book based decentralized exchange was decommissioned in [BEP151](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP151.md). With the quick evolution of BSC, the Beacon Chain has become a burden. The cross-chain bridge that connects the two chains slows down the development iteration and always exposes BNB to a certain level of security vulnerabilities. It's time to take a step further and migrate the functionality of Beacon Chain to BSC, allowing Beacon Chain to retire.
> 
> ## 5. Specification
> ### 5.1 Introduction
> The Beacon Chain currently possesses several key functionalities:
> 
> 1. Cryptocurrency management platform. The Beacon Chain mainnet currently supports a hundred kinds of [BEP2](https://explorer.bnbchain.org/assets/bep2) and [BEP8](https://explorer.bnbchain.org/assets/bep8) tokens. These tokens have value and can be circulated on the Beacon Chain or transferred across different chains using protocols such as [BEP3](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP3.md).
> 2. The staking layer of BSC. The BSC utilizes the POSA consensus algorithm. It delegates staking election and reward distribution functions to the Beacon Chain. This design choice was based on the fact that the Beacon Chain is built on the cosmos-sdk architecture, which already includes a well-developed staking module that can be reused.
> 3. The governance layer of BSC. For similar reasons, the governance functionality of BSC is delegated to the Beacon Chain as well. The governance vote and tally happen on Beacon Chain, and the execution plan is delivered to the BSC through cross chain communication protocol.
> 
> Therefore, we have three separate BEPs that discuss how to migrate these functionalities or valuable assets to BSC.
> 
> 1. [BEP-299](https://github.com/bnb-chain/BEPs/pull/299): This BEP presents a secure and trustless way for users to recover their assets on the BSC once the Beacon chain stops running.
> 2. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294): This BEP allows BNB holders to stake BNB to the specified validators and get staking rewards on the BSC side directly. To ensure network security, the migration of Staking voting power is designed to be seamless. This means that both the Beacon Chain and BSC's staking modules will coexist and function simultaneously during the migration process.
> 3. [BEP297](https://github.com/bnb-chain/BEPs/pull/297): This BEP allows community members to submit proposals directly on the BSC network. The governance module is fully compatible with [Tally](https://www.tally.xyz/).
> 
> ### 5.2 Multiple Phases
> To accomplish BC Fusion, there will be several preparation and post-action steps involved, connecting these BEPs together. Thus, BC Fusion is divided into multiple stages:
> 
> ![multiple phases](https://raw.githubusercontent.com/bnb-chain/BEPs/9649944c2a41b05e5ca59d5fa18b592a0ee600ee/BEPs/assets/bep-333/phases.png)
> 
> #### 5.2.1 First Sunset Fork
> Due to the requirement of returning cryptocurrency to the user's wallet in order to migrate funds to BSC through [BEP-299](https://github.com/bnb-chain/BEPs/pull/299). The Beacon Chain will disable specific types of transactions to encourage users to keep their funds in their own wallets. The following types of Beacon chain transactions will be disabled: **TimeLockMsg**, **TimeRelockMsg**, **FreezeMsg**, **IssueMsg**, **MintMsg**, **IssueMiniMsg**, **HTLTMsg**, **DepositHTLTMsg**.
> 
> During the migration process, Beacon Chain prohibits the creation and editing of validators to prevent conflicts with validators created on BSC side. New delegations will also be prohibited. The following types of Beacon chain transactions will be disabled: **MsgCreateValidatorOpen**, **MsgCreateSideChainValidator**, **MsgCreateSideChainValidatorWithVoteAddr**, **MsgEditSideChainValidatorWithVoteAddr**, **MsgSideChainDelegate**, **MsgSideChainReDelegate**.
> 
> To ensure that the voting power migration process is not maliciously manipulated, the Governance module will be automatically disabled when the voting power is below 5M BNB.
> 
> The above-mentioned features will be enabled in Beacon Chain **FirstSunsetFork**.
> 
> #### 5.2.2 BSC Feynman Hardfork
> [BEP-294](https://github.com/bnb-chain/BEPs/pull/294), [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) and [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) will be deployed in the BSC **Feynman** hard fork.
> 
> 1. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) will take effect immediately. Validators created on BSC will receive triple voting power when staking an equal amount of BNB. This encourages the transfer of voting power from the Beacon Chain to BSC.
> 2. The [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) governance functionality will not be activated immediately after the hardfork. It will only be automatically enabled once more than 10 million BNB are migrated to BSC.
> 3. The smart contract of [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) is not available as the merkel root in the smart contract is still empty at this time. Only after the Beacon Chain comes to a complete halt, the Token Migration feature will be initiated by setting the Merkle root for balance dump through governance.
> 4. Cross-chain re-delegation, which allows users to un-delegate their stakes from Beacon Chain and then delegate them on BSC in one Beacon Chain transaction,  will be enabled after governance opening the related cross-chain channel.
> 
> An important wallet will be introduced in this hardfork: **AssetProtector.** **AssetProtector** is a multi-signature wallet controlled by the core dev team at the beginning. It can:
> 
> * Pause and unpause the staking, governance and token migration contract in emergency situations.
> * Forbidden a specific account to perform any operations in the staking contract.
> 
> #### 5.2.3 Second Sunset Fork
> After transferring more than two-thirds of the voting power to BSC, the Beacon Chain must restrict additional transaction types and automatically execute specific logic to ensure the return of funds to users' wallets. The following transactions will be disabled: **MsgSideChainSubmitProposal**.
> 
> All TimeLock and AtomicSwap will automatica [...]

2024-10-25 12:46 UTC, 10208612 commented
@

2024-10-27 06:08 UTC, Rhahgan21 reviewed
Be patient

2024-11-11 19:18 UTC, WeerayutW commented
Wallet

2024-11-11 20:00 UTC, draghtnight reviewed
@

>

2024-11-12 00:37 UTC, Comandante318 reviewed
😎

2024-11-13 01:37 UTC, yener35 commented
****

2024-11-13 01:37 UTC, yener35 commented
[]()

2024-11-13 06:41 UTC, Rhahgan21 reviewed
It will be easy

2024-11-13 14:31 UTC, yener35 commented
merhaba dana yeniyim bana biraz yapmam gereken hakkında bilgi
verebilirmisin yardıma ihtiyacım var.teşekkürler

Rhahgan21 ***@***.***>, 13 Kas 2024 Çar, 09:41 tarihinde şunu
yazdı:

> ***@***.**** commented on this pull request.
>
> It will be easy
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bnb-chain/BEPs/pull/333#pullrequestreview-2432041102>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKDE7D4LGR7JMTYYERTBNOD2ALYCPAVCNFSM6AAAAAA77AAZNCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMZSGA2DCMJQGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-11-21 21:00 UTC, Tanimola50 approved these changes

2024-11-22 12:37 UTC, amiralighass commented
Nice ☺️

2024-11-24 07:06 UTC, WTDuck2255 commented
> BEP: 333
>   Title: BNB Chain Fusion
>   Status: Draft
>   Type: Standards
>   Created: 2023-11-29
> # BEP-333: BNB Chain Fusion
> [BEP-333: BNB Chain Fusion](#bep-333-bnb-chain-fusion)
> 
> * [1. Summary](#1-summary)
> * [2. Abstract](#2-abstract)
> * [3. Status](#3-status)
> * [4. Motivation](#4-motivation)
> * [5. Specification](#5-specification)
>   
>   * [5.1 Introduction](#51-introduction)
>   * [5.2 Multiple Phases](#52-multiple-phases)
> * [6. License](#6-license)
> 
> ## 1. Summary
> This BEP proposes to securely and smoothly transit the BNB Beacon Chain and BNB Smart Chain (BSC) from a dual-chain structure into a single chain structure and decommission the Beacon Chain.
> 
> ## 2. Abstract
> BNB Chain Fusion (BC Fusion) is a major achievement for BNB Chain. It helps overcome legacy services and technical debt, enabling faster iteration and development. BC Fusion includes three sub-BEPs:
> 
> * [BEP-294: BSC Native Staking](https://github.com/bnb-chain/BEPs/pull/294)
> * [BEP-297: BSC Native Governance](https://github.com/bnb-chain/BEPs/pull/297)
> * [BEP-299: Token Migration after BC Fusion](https://github.com/bnb-chain/BEPs/pull/299)
> 
> This BEP primarily proposes strategic planning and coordination for organizing these BEPs. The goal is to facilitate the secure and seamless implementation of BC Fusion.
> 
> ## 3. Status
> This BEP is a draft.
> 
> ## 4. Motivation
> BNB Beacon Chain is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. Besides this, Beacon Chain and BSC is a dual-chain structure: Beacon Chain helps to enhance the security of BSC as a staking and governance layer. With the rise of various other forms of Dex, order-book based decentralized exchange was decommissioned in [BEP151](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP151.md). With the quick evolution of BSC, the Beacon Chain has become a burden. The cross-chain bridge that connects the two chains slows down the development iteration and always exposes BNB to a certain level of security vulnerabilities. It's time to take a step further and migrate the functionality of Beacon Chain to BSC, allowing Beacon Chain to retire.
> 
> ## 5. Specification
> ### 5.1 Introduction
> The Beacon Chain currently possesses several key functionalities:
> 
> 1. Cryptocurrency management platform. The Beacon Chain mainnet currently supports a hundred kinds of [BEP2](https://explorer.bnbchain.org/assets/bep2) and [BEP8](https://explorer.bnbchain.org/assets/bep8) tokens. These tokens have value and can be circulated on the Beacon Chain or transferred across different chains using protocols such as [BEP3](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP3.md).
> 2. The staking layer of BSC. The BSC utilizes the POSA consensus algorithm. It delegates staking election and reward distribution functions to the Beacon Chain. This design choice was based on the fact that the Beacon Chain is built on the cosmos-sdk architecture, which already includes a well-developed staking module that can be reused.
> 3. The governance layer of BSC. For similar reasons, the governance functionality of BSC is delegated to the Beacon Chain as well. The governance vote and tally happen on Beacon Chain, and the execution plan is delivered to the BSC through cross chain communication protocol.
> 
> Therefore, we have three separate BEPs that discuss how to migrate these functionalities or valuable assets to BSC.
> 
> 1. [BEP-299](https://github.com/bnb-chain/BEPs/pull/299): This BEP presents a secure and trustless way for users to recover their assets on the BSC once the Beacon chain stops running.
> 2. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294): This BEP allows BNB holders to stake BNB to the specified validators and get staking rewards on the BSC side directly. To ensure network security, the migration of Staking voting power is designed to be seamless. This means that both the Beacon Chain and BSC's staking modules will coexist and function simultaneously during the migration process.
> 3. [BEP297](https://github.com/bnb-chain/BEPs/pull/297): This BEP allows community members to submit proposals directly on the BSC network. The governance module is fully compatible with [Tally](https://www.tally.xyz/).
> 
> ### 5.2 Multiple Phases
> To accomplish BC Fusion, there will be several preparation and post-action steps involved, connecting these BEPs together. Thus, BC Fusion is divided into multiple stages:
> 
> ![multiple phases](https://raw.githubusercontent.com/bnb-chain/BEPs/9649944c2a41b05e5ca59d5fa18b592a0ee600ee/BEPs/assets/bep-333/phases.png)
> 
> #### 5.2.1 First Sunset Fork
> Due to the requirement of returning cryptocurrency to the user's wallet in order to migrate funds to BSC through [BEP-299](https://github.com/bnb-chain/BEPs/pull/299). The Beacon Chain will disable specific types of transactions to encourage users to keep their funds in their own wallets. The following types of Beacon chain transactions will be disabled: **TimeLockMsg**, **TimeRelockMsg**, **FreezeMsg**, **IssueMsg**, **MintMsg**, **IssueMiniMsg**, **HTLTMsg**, **DepositHTLTMsg**.
> 
> During the migration process, Beacon Chain prohibits the creation and editing of validators to prevent conflicts with validators created on BSC side. New delegations will also be prohibited. The following types of Beacon chain transactions will be disabled: **MsgCreateValidatorOpen**, **MsgCreateSideChainValidator**, **MsgCreateSideChainValidatorWithVoteAddr**, **MsgEditSideChainValidatorWithVoteAddr**, **MsgSideChainDelegate**, **MsgSideChainReDelegate**.
> 
> To ensure that the voting power migration process is not maliciously manipulated, the Governance module will be automatically disabled when the voting power is below 5M BNB.
> 
> The above-mentioned features will be enabled in Beacon Chain **FirstSunsetFork**.
> 
> #### 5.2.2 BSC Feynman Hardfork
> [BEP-294](https://github.com/bnb-chain/BEPs/pull/294), [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) and [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) will be deployed in the BSC **Feynman** hard fork.
> 
> 1. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) will take effect immediately. Validators created on BSC will receive triple voting power when staking an equal amount of BNB. This encourages the transfer of voting power from the Beacon Chain to BSC.
> 2. The [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) governance functionality will not be activated immediately after the hardfork. It will only be automatically enabled once more than 10 million BNB are migrated to BSC.
> 3. The smart contract of [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) is not available as the merkel root in the smart contract is still empty at this time. Only after the Beacon Chain comes to a complete halt, the Token Migration feature will be initiated by setting the Merkle root for balance dump through governance.
> 4. Cross-chain re-delegation, which allows users to un-delegate their stakes from Beacon Chain and then delegate them on BSC in one Beacon Chain transaction,  will be enabled after governance opening the related cross-chain channel.
> 
> An important wallet will be introduced in this hardfork: **AssetProtector.** **AssetProtector** is a multi-signature wallet controlled by the core dev team at the beginning. It can:
> 
> * Pause and unpause the staking, governance and token migration contract in emergency situations.
> * Forbidden a specific account to perform any operations in the staking contract.
> 
> #### 5.2.3 Second Sunset Fork
> After transferring more than two-thirds of the voting power to BSC, the Beacon Chain must restrict additional transaction types and automatically execute specific logic to ensure the return of funds to users' wallets. The following transactions will be disabled: **MsgSideChainSubmitProposal**.
> 
> All TimeLock and AtomicSwap will automatica [...]

2024-11-25 22:28 UTC, octavio12345300 reviewed
listo

2024-11-28 00:16 UTC, yener35 commented
****

2024-12-02 09:50 UTC, ABDALLA10FATHY approved these changes

2024-12-03 06:58 UTC, homelandmusic commented
its dec 3rd, i checked the recovery dapp to migrate my cardano on bep2 but it still says : You don't have any assets on the BNB Beacon Chain.
any body know how to di it ?

2024-12-06 02:41 UTC, noodles5941 commented
I am having the same issue as poster above. I am trying to migrate my BNB coins, since I missed the deadline period. I was able to sync my Exodus wallet to 'BNB chain wallet' and 'Trust Wallet', but it does not show my share of BNB coins on there. It also states that I have no assets when I connect to the 'token recovery tool'
Can anyone please help with this??

2024-12-07 17:58 UTC, 10208612 commented on BEPs/BEP333.md
> +The content is licensed under [CC0](https://creativecommons.org/publicdomain/zero/1.0/).
https://github.com/node-real/bnbchainlist/blob/main/utils%2Fchains.json

2024-12-08 03:51 UTC, Comandante318 reviewed
?

2024-12-08 17:15 UTC, 10208612 approved these changes

2024-12-10 18:29 UTC, mfxrhxn reviewed
Hmm

2024-12-15 03:17 UTC, octavio12345300 approved these changes

2024-12-15 03:18 UTC, octavio12345300 approved these changes

2024-12-15 03:18 UTC, octavio12345300 approved these changes

2024-12-15 03:19 UTC, octavio12345300 approved these changes

2024-12-18 06:27 UTC, dannylincs commented
please I tried to Know if I can recover my Rune but it saying that I cannot recover "unbounded"
please what else can I do

2024-12-19 04:41 UTC, Milesxx28 approved these changes
Review

2024-12-19 04:41 UTC, Milesxx28 commented on BEPs/BEP333.md
> +  - [1. Summary](#1-summary)
- [ ] 75,8756.88

2024-12-28 17:02 UTC, Ekkanit commented
BEP29

2024-12-28 17:03 UTC, Ekkanit commented
BEP20

2024-12-31 07:25 UTC, octavio12345300 reviewed
l

2025-01-07 11:34 UTC, JlynnD31 approved these changes

2025-01-27 09:18 UTC, Rjsoon38afk commented
Wow

2025-01-27 11:45 UTC, Yasersarhadikarbasak commented
سلام چطوری به  بایننس فیوژن دسترسی پیدا کنم خواهش میکنم کمکم کنید

2025-01-28 02:17 UTC, Aldocapurro approved these changes

2025-01-30 05:28 UTC, Aldocapurro approved these changes

2025-02-25 03:08 UTC, Armanidashh commented on BEPs/BEP333.md
> +  - [1. Summary](#1-summary)
1

2025-02-25 03:10 UTC, Armanidashh reviewed
Approve

2025-02-27 06:46 UTC, Aldocapurro approved these changes

2025-03-11 07:49 UTC, Carlo0704 approved these changes

2025-03-14 09:46 UTC, SrichonBoon commented on BEPs/BEP333.md
> +   currently supports a hundred kinds of [BEP2](https://explorer.bnbchain.org/assets/bep2)
Ok.

2025-03-14 19:36 UTC, Ifytech18 commented
Good

2025-03-23 12:29 UTC, 10208612 approved these changes

2025-03-26 14:55 UTC, JlynnD31 commented
Approved

On Wed, Mar 26, 2025, 10:21 AM alexguzman124 ***@***.***>
wrote:

> Duplicado de #
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bnb-chain/BEPs/pull/333#issuecomment-2754605572>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFMYJ7TAYR5FNE5ER3HLVIT2WKZWLAVCNFSM6AAAAAA77AAZNCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDONJUGYYDKNJXGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
> [image: alexguzman124]*alexguzman124* left a comment (bnb-chain/BEPs#333)
> <https://github.com/bnb-chain/BEPs/pull/333#issuecomment-2754605572>
>
> Duplicado de #
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bnb-chain/BEPs/pull/333#issuecomment-2754605572>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFMYJ7TAYR5FNE5ER3HLVIT2WKZWLAVCNFSM6AAAAAA77AAZNCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDONJUGYYDKNJXGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-03-26 17:07 UTC, abo-L commented
> listo

2025-03-26 17:07 UTC, abo-L approved these changes

2025-03-27 10:58 UTC, Ifytech18 commented on BEPs/BEP333.md
> +The content is licensed under [CC0](https://creativecommons.org/publicdomain/zero/1.0/).
Ok

2025-03-28 09:54 UTC, 0599394760 commented on BEPs/BEP333.md
> +  - [1. Summary](#1-summary)
I not understand

2025-03-29 12:18 UTC, abo-L commented on BEPs/BEP333.md
> +  - [1. Summary](#1-summary)
> - [ ] 75,8756.88

2025-03-29 12:46 UTC, Veeezo commented on BEPs/BEP333.md
> +  - [1. Summary](#1-summary)
75,8756.88

2025-04-01 08:38 UTC, char23-web reviewed
Wow

2025-04-01 09:58 UTC, abo-L commented on BEPs/BEP333.md
> +The content is licensed under [CC0](https://creativecommons.org/publicdomain/zero/1.0/).
BTC

2025-04-02 17:15 UTC, Ifytech18 commented on BEPs/BEP333.md
> +  - [1. Summary](#1-summary)
75,8756.88

2025-04-04 21:37 UTC, Mamunkhan9032 commented
forcodedancing:chain_fusion

2025-04-05 09:17 UTC, octavio12345300 approved these changes
Listo,

2025-04-06 13:03 UTC, Ifytech18 commented
Ok

2025-04-10 22:20 UTC, Ifytech18 commented on BEPs/BEP333.md
> +  - [1. Summary](#1-summary)
Ok

2025-04-10 22:22 UTC, Ifytech18 approved these changes

2025-05-09 22:03 UTC, AliAlkhtri approved these changes

2025-05-27 23:12 UTC, mustafacryptolife commented
[]()

2025-05-31 10:51 UTC, Stepheng124 reviewed
Get iCloud from the Microsoft Store https://apps.microsoft.com/detail/9pktq5699m62?ocid=webpdpshare

2025-06-24 20:06 UTC, Gb2real reviewed
I can do it easily

2025-07-10 21:05 UTC, ramibn commented
> BEP: 333
>   Title: BNB Chain Fusion
>   Status: Draft
>   Type: Standards
>   Created: 2023-11-29
> # BEP-333: BNB Chain Fusion
> [BEP-333: BNB Chain Fusion](#bep-333-bnb-chain-fusion)
> 
> * [1. Summary](#1-summary)
> * [2. Abstract](#2-abstract)
> * [3. Status](#3-status)
> * [4. Motivation](#4-motivation)
> * [5. Specification](#5-specification)
>   
>   * [5.1 Introduction](#51-introduction)
>   * [5.2 Multiple Phases](#52-multiple-phases)
> * [6. License](#6-license)
> 
> ## 1. Summary
> This BEP proposes to securely and smoothly transit the BNB Beacon Chain and BNB Smart Chain (BSC) from a dual-chain structure into a single chain structure and decommission the Beacon Chain.
> 
> ## 2. Abstract
> BNB Chain Fusion (BC Fusion) is a major achievement for BNB Chain. It helps overcome legacy services and technical debt, enabling faster iteration and development. BC Fusion includes three sub-BEPs:
> 
> * [BEP-294: BSC Native Staking](https://github.com/bnb-chain/BEPs/pull/294)
> * [BEP-297: BSC Native Governance](https://github.com/bnb-chain/BEPs/pull/297)
> * [BEP-299: Token Migration after BC Fusion](https://github.com/bnb-chain/BEPs/pull/299)
> 
> This BEP primarily proposes strategic planning and coordination for organizing these BEPs. The goal is to facilitate the secure and seamless implementation of BC Fusion.
> 
> ## 3. Status
> This BEP is a draft.
> 
> ## 4. Motivation
> BNB Beacon Chain is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. Besides this, Beacon Chain and BSC is a dual-chain structure: Beacon Chain helps to enhance the security of BSC as a staking and governance layer. With the rise of various other forms of Dex, order-book based decentralized exchange was decommissioned in [BEP151](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP151.md). With the quick evolution of BSC, the Beacon Chain has become a burden. The cross-chain bridge that connects the two chains slows down the development iteration and always exposes BNB to a certain level of security vulnerabilities. It's time to take a step further and migrate the functionality of Beacon Chain to BSC, allowing Beacon Chain to retire.
> 
> ## 5. Specification
> ### 5.1 Introduction
> The Beacon Chain currently possesses several key functionalities:
> 
> 1. Cryptocurrency management platform. The Beacon Chain mainnet currently supports a hundred kinds of [BEP2](https://explorer.bnbchain.org/assets/bep2) and [BEP8](https://explorer.bnbchain.org/assets/bep8) tokens. These tokens have value and can be circulated on the Beacon Chain or transferred across different chains using protocols such as [BEP3](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP3.md).
> 2. The staking layer of BSC. The BSC utilizes the POSA consensus algorithm. It delegates staking election and reward distribution functions to the Beacon Chain. This design choice was based on the fact that the Beacon Chain is built on the cosmos-sdk architecture, which already includes a well-developed staking module that can be reused.
> 3. The governance layer of BSC. For similar reasons, the governance functionality of BSC is delegated to the Beacon Chain as well. The governance vote and tally happen on Beacon Chain, and the execution plan is delivered to the BSC through cross chain communication protocol.
> 
> Therefore, we have three separate BEPs that discuss how to migrate these functionalities or valuable assets to BSC.
> 
> 1. [BEP-299](https://github.com/bnb-chain/BEPs/pull/299): This BEP presents a secure and trustless way for users to recover their assets on the BSC once the Beacon chain stops running.
> 2. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294): This BEP allows BNB holders to stake BNB to the specified validators and get staking rewards on the BSC side directly. To ensure network security, the migration of Staking voting power is designed to be seamless. This means that both the Beacon Chain and BSC's staking modules will coexist and function simultaneously during the migration process.
> 3. [BEP297](https://github.com/bnb-chain/BEPs/pull/297): This BEP allows community members to submit proposals directly on the BSC network. The governance module is fully compatible with [Tally](https://www.tally.xyz/).
> 
> ### 5.2 Multiple Phases
> To accomplish BC Fusion, there will be several preparation and post-action steps involved, connecting these BEPs together. Thus, BC Fusion is divided into multiple stages:
> 
> ![multiple phases](https://raw.githubusercontent.com/bnb-chain/BEPs/9649944c2a41b05e5ca59d5fa18b592a0ee600ee/BEPs/assets/bep-333/phases.png)
> 
> #### 5.2.1 First Sunset Fork
> Due to the requirement of returning cryptocurrency to the user's wallet in order to migrate funds to BSC through [BEP-299](https://github.com/bnb-chain/BEPs/pull/299). The Beacon Chain will disable specific types of transactions to encourage users to keep their funds in their own wallets. The following types of Beacon chain transactions will be disabled: **TimeLockMsg**, **TimeRelockMsg**, **FreezeMsg**, **IssueMsg**, **MintMsg**, **IssueMiniMsg**, **HTLTMsg**, **DepositHTLTMsg**.
> 
> During the migration process, Beacon Chain prohibits the creation and editing of validators to prevent conflicts with validators created on BSC side. New delegations will also be prohibited. The following types of Beacon chain transactions will be disabled: **MsgCreateValidatorOpen**, **MsgCreateSideChainValidator**, **MsgCreateSideChainValidatorWithVoteAddr**, **MsgEditSideChainValidatorWithVoteAddr**, **MsgSideChainDelegate**, **MsgSideChainReDelegate**.
> 
> To ensure that the voting power migration process is not maliciously manipulated, the Governance module will be automatically disabled when the voting power is below 5M BNB.
> 
> The above-mentioned features will be enabled in Beacon Chain **FirstSunsetFork**.
> 
> #### 5.2.2 BSC Feynman Hardfork
> [BEP-294](https://github.com/bnb-chain/BEPs/pull/294), [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) and [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) will be deployed in the BSC **Feynman** hard fork.
> 
> 1. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) will take effect immediately. Validators created on BSC will receive triple voting power when staking an equal amount of BNB. This encourages the transfer of voting power from the Beacon Chain to BSC.
> 2. The [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) governance functionality will not be activated immediately after the hardfork. It will only be automatically enabled once more than 10 million BNB are migrated to BSC.
> 3. The smart contract of [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) is not available as the merkel root in the smart contract is still empty at this time. Only after the Beacon Chain comes to a complete halt, the Token Migration feature will be initiated by setting the Merkle root for balance dump through governance.
> 4. Cross-chain re-delegation, which allows users to un-delegate their stakes from Beacon Chain and then delegate them on BSC in one Beacon Chain transaction,  will be enabled after governance opening the related cross-chain channel.
> 
> An important wallet will be introduced in this hardfork: **AssetProtector.** **AssetProtector** is a multi-signature wallet controlled by the core dev team at the beginning. It can:
> 
> * Pause and unpause the staking, governance and token migration contract in emergency situations.
> * Forbidden a specific account to perform any operations in the staking contract.
> 
> #### 5.2.3 Second Sunset Fork
> After transferring more than two-thirds of the voting power to BSC, the Beacon Chain must restrict additional transaction types and automatically execute specific logic to ensure the return of funds to users' wallets. The following transactions will be disabled: **MsgSideChainSubmitProposal**.
> 
> All TimeLock and AtomicSwap will automatica [...]

2025-08-03 01:51 UTC, muyiwa12 reviewed
Wow

2025-08-03 07:38 UTC, vahidrezaiy approved these changes

2025-08-03 23:29 UTC, octavio12345300 approved these changes
List

2025-11-10 16:50 UTC, estrellita2121 commented
> <pre>
>   BEP: 333
>   Title: BNB Chain Fusion
>   Status: Draft
>   Type: Standards
>   Created: 2023-11-29
> </pre>
> 
> # BEP-333: BNB Chain Fusion
> 
> [BEP-333: BNB Chain Fusion](#bep-333-bnb-chain-fusion)
>   - [1. Summary](#1-summary)
>   - [2. Abstract](#2-abstract)
>   - [3. Status](#3-status)
>   - [4. Motivation](#4-motivation)
>   - [5. Specification](#5-specification)
>       - [5.1 Introduction](#51-introduction)
>       - [5.2 Multiple Phases](#52-multiple-phases)
>   - [6. License](#6-license)
> 
> ## 1. Summary
> 
> This BEP proposes to securely and smoothly transit the BNB Beacon Chain and BNB Smart Chain (BSC) from a dual-chain structure into a single chain structure and decommission the Beacon Chain.
> 
> ## 2. Abstract
> 
> BNB Chain Fusion (BC Fusion) is a major achievement for BNB Chain. It helps overcome legacy services and technical debt, enabling faster iteration and development. BC Fusion includes three sub-BEPs:
> 
> - [BEP-294: BSC Native Staking](https://github.com/bnb-chain/BEPs/pull/294)
> 
> - [BEP-297: BSC Native Governance](https://github.com/bnb-chain/BEPs/pull/297)
> 
> - [BEP-299: Token Migration after BC Fusion](https://github.com/bnb-chain/BEPs/pull/299)
> 
> This BEP primarily proposes strategic planning and coordination for organizing these BEPs. The goal is to facilitate the secure and seamless implementation of BC Fusion.
> 
> ## 3. Status
> 
> This BEP is a draft.
> 
> ## 4. Motivation
> 
> BNB Beacon Chain is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. Besides this, Beacon Chain and BSC is a dual-chain structure: Beacon Chain helps to enhance the security of BSC as a staking and governance layer. With the rise of various other forms of Dex, order-book based decentralized exchange was decommissioned in [BEP151](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP151.md). With the quick evolution of BSC, the Beacon Chain has become a burden. The cross-chain bridge that connects the two chains slows down the development iteration and always exposes BNB to a certain level of security vulnerabilities. It\'s time to take a step further and migrate the functionality of Beacon Chain to BSC, allowing Beacon Chain to retire.
> 
> ## 5. Specification
> 
> ### 5.1 Introduction
> 
> The Beacon Chain currently possesses several key functionalities:
> 
> 1. Cryptocurrency management platform. The Beacon Chain mainnet currently supports a hundred kinds of [BEP2](https://explorer.bnbchain.org/assets/bep2) and [BEP8](https://explorer.bnbchain.org/assets/bep8) tokens. These tokens have value and can be circulated on the Beacon Chain or transferred across different chains using protocols such as [BEP3](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP3.md).
> 
> 2. The staking layer of BSC. The BSC utilizes the POSA consensus algorithm. It delegates staking election and reward distribution functions to the Beacon Chain. This design choice was based on the fact that the Beacon Chain is built on the cosmos-sdk architecture, which already includes a well-developed staking module that can be reused.
> 
> 3. The governance layer of BSC. For similar reasons, the governance functionality of BSC is delegated to the Beacon Chain as well. The governance vote and tally happen on Beacon Chain, and the execution plan is delivered to the BSC through cross chain communication protocol.
> 
> Therefore, we have three separate BEPs that discuss how to migrate these functionalities or valuable assets to BSC.
> 
> 1. [BEP-299](https://github.com/bnb-chain/BEPs/pull/299): This BEP presents a secure and trustless way for users to recover their assets on the BSC once the Beacon chain stops running.
> 
> 2. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294): This BEP allows BNB holders to stake BNB to the specified validators and get staking rewards on the BSC side directly. To ensure network security, the migration of Staking voting power is designed to be seamless. This means that both the Beacon Chain and BSC\'s staking modules will coexist and function simultaneously during the migration process.
> 
> 3. [BEP297](https://github.com/bnb-chain/BEPs/pull/297): This BEP allows community members to submit proposals directly on the BSC network. The governance module is fully compatible with [Tally](https://www.tally.xyz/).
> 
> ### 5.2 Multiple Phases
> 
> To accomplish BC Fusion, there will be several preparation and post-action steps involved, connecting these BEPs together. Thus, BC Fusion is divided into multiple stages:
> 
> ![multiple phases](https://raw.githubusercontent.com/bnb-chain/BEPs/9649944c2a41b05e5ca59d5fa18b592a0ee600ee/BEPs/assets/bep-333/phases.png)
> 
> #### 5.2.1 First Sunset Fork
> 
> Due to the requirement of returning cryptocurrency to the user\'s wallet in order to migrate funds to BSC through [BEP-299](https://github.com/bnb-chain/BEPs/pull/299). The Beacon Chain will disable specific types of transactions to encourage users to keep their funds in their own wallets. The following types of Beacon chain transactions will be disabled: **TimeLockMsg**, **TimeRelockMsg**, **FreezeMsg**, **IssueMsg**, **MintMsg**, **IssueMiniMsg**, **HTLTMsg**, **DepositHTLTMsg**.
> 
> During the migration process, Beacon Chain prohibits the creation and editing of validators to prevent conflicts with validators created on BSC side. New delegations will also be prohibited. The following types of Beacon chain transactions will be disabled: **MsgCreateValidatorOpen**, **MsgCreateSideChainValidator**, **MsgCreateSideChainValidatorWithVoteAddr**, **MsgEditSideChainValidatorWithVoteAddr**, **MsgSideChainDelegate**, **MsgSideChainReDelegate**.
> 
> To ensure that the voting power migration process is not maliciously manipulated, the Governance module will be automatically disabled when the voting power is below 5M BNB.
> 
> The above-mentioned features will be enabled in Beacon Chain **FirstSunsetFork**.
> 
> #### 5.2.2 BSC Feynman Hardfork
> 
> [BEP-294](https://github.com/bnb-chain/BEPs/pull/294), [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) and [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) will be deployed in the BSC **Feynman** hard fork.
> 
> 1. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) will take effect immediately. Validators created on BSC will receive triple voting power when staking an equal amount of BNB. This encourages the transfer of voting power from the Beacon Chain to BSC.
> 
> 2. The [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) governance functionality will not be activated immediately after the hardfork. It will only be automatically enabled once more than 10 million BNB are migrated to BSC.
> 
> 3. The smart contract of [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) is not available as the merkel root in the smart contract is still empty at this time. Only after the Beacon Chain comes to a complete halt, the Token Migration feature will be initiated by setting the Merkle root for balance dump through governance.
> 
> 4. Cross-chain re-delegation, which allows users to un-delegate their stakes from Beacon Chain and then delegate them on BSC in one Beacon Chain transaction,  will be enabled after governance opening the related cross-chain channel.
> 
> An important wallet will be introduced in this hardfork: **AssetProtector.** **AssetProtector** is a multi-signature wallet controlled by the core dev team at the beginning. It can:
> 
> - Pause and unpause the staking, governance and token migration contract in emergency situations.
> 
> - Forbidden a specific account to perform any operations in the staking contract.
> 
> #### 5.2.3 Second Sunset Fork
> 
> After transferring more than two-thirds of the voting power to BSC, the Beacon Chain must restrict additional transaction types and automatically execute specific logic to ensure the return of funds to users\' wallets. The following transactio [...]

2025-11-26 12:20 UTC, johnny5OO approved these changes

2026-02-01 05:47 UTC, Castro1g commented
forcodedancing:chain_fusion

2026-02-01 05:48 UTC, Castro1g commented
```html

```

2026-02-01 10:44 UTC, estrellita2121 commented
El sáb, 31 de ene de 2026, 11:48 p.m., Castro1g ***@***.***>
escribió:

> *Castro1g* left a comment (bnb-chain/BEPs#333)
> <https://github.com/bnb-chain/BEPs/pull/333#issuecomment-3830424416>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bnb-chain/BEPs/pull/333#issuecomment-3830424416>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BPZMLIIOFB4OC4NYONC44MD4JWHS5AVCNFSM6AAAAAA77AAZNCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTQMZQGQZDINBRGY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2026-02-01 11:15 UTC, renataveganoriega12-blip reviewed
https://github.com/bnb-chain/BEPs/issues/666#issue-3881833428

2026-02-01 11:15 UTC, renataveganoriega12-blip commented on BEPs/BEP333.md
forcodedancing:chain_fusion

2026-02-01 11:19 UTC, renataveganoriega12-blip commented
forcodedancing:chain_fusion

2026-02-01 11:19 UTC, renataveganoriega12-blip commented
> [](url)

2026-03-20 02:15 UTC, souihci0805-netizen commented on BEPs/BEP333.md
😁

2026-03-20 02:19 UTC, souihci0805-netizen commented
あの

2026-03-20 02:21 UTC, souihci0805-netizen commented
****

2026-04-12 14:58 UTC, vcarder24-hue commented
Wow,, I need a lot of help and computers equipment A.S.A.P.
I am overwhelmed right now. Thank you for your help

2026-04-27 23:05 UTC, Anos995 reviewed
٥

2026-04-27 23:05 UTC, Anos995 approved these changes

2026-04-27 23:06 UTC, Anos995 approved these changes

2026-04-27 23:08 UTC, Anos995 requested changes
٥

2026-08-01 21:24 UTC, Vingithub74 reviewed
Approve

2026-08-10 15:44 UTC, Veeezo commented on BEPs/BEP333.md
> forcodedancing:chain_fusion

2026-09-28 00:59 UTC, Mohammedsapry approved these changes