BEP4: 256-bit Tokens
bnb-chain/BEPs pull request #4
Opened 2019-05-01 00:30 UTC by wjmelements

#### Changes
This adds a proposal to increase the number of bits for tokens from 63 to 256.
Reviewers @notatestuser @huangsuyu

2019-05-05 11:32 UTC, darren-liu commented
Even though there exist many

2020-11-14 03:28 UTC, lacvinhky commented on BEP4.md
> +* 119 billion Dogecoin
Ọ

2021-02-09 22:34 UTC, Jonsms1 approved these changes

2021-02-09 22:36 UTC, Jonsms1 approved these changes

2021-04-12 16:06 UTC, nguyenducsang commented
Ok

2021-04-12 16:11 UTC, nguyenducsang commented on BEP4.md
> +* 119 billion Dogecoin
Ok

2021-04-15 17:59 UTC, nguyenducsang requested changes
Hâ

2022-08-11 04:42 UTC, trastvolt commented
wjmelements:bep-change-token-units

2022-12-02 01:38 UTC, brilliant-lx commented
outdate, archive it.

2022-12-02 01:38 UTC, closed without merging